### ISSUE TITLE
Delete RabbitMQ Queue on simulation finish

### ISSUE THREAD

**Issue by mesalas** [sbenthall/SHARKFin#104]
Once ammps/sharkfin simulations using RabbitMQ finish, the queue used for the pair to communicate should be deleted.
This will free up memory on the RabbitMQ server and avoid contamination between simulation using the same queue name if we forget to restart the RabbitMQ server instance.

**Comment by sbenthall** [comment]
Should this be done before Chum?
I can look into how to do this if you think the SHARKFin code is the right place to do this.
Or maybe we should meet about this to figure out were to put in the queue killer script.

**Comment by mesalas** [comment]
I think it only a matter of adding a line or two when sharkfin wraps up. Ill take a look at the rabbitMQ documentation to see how we close queues.

**Comment by mesalas** [comment]
Ok Seems like we can do it from python. 
https://pika.readthedocs.io/en/latest/modules/channel.html#pika.channel.Channel.queue_delete .
and in C# https://www.rabbitmq.com/dotnet-api-guide.html#connection-and-channel-lifespan .
We probably want to do it from C# as its where the queue is created in the first place

**Comment by sbenthall** [comment]
Sounds like:
 - AMMPS should destroy the named queue that it creates
 - sharkfin should destroy the ANONYMOUS CALLBACK QUEUE that it creates!

**Comment by sbenthall** [comment]
see #111
