### ISSUE TITLE
Error building ammps binary

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#108]
Related to #107 -- finding the only path I could to `amm.engine` and running the command in the README did not work. 

```
$ dotnet build ammps_bin/amm.engine -o amm_binary
Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

/home/sb/projects/ufm/local-ammps-test/ammps_sharkfin_container/container_contents/ammps_bin/amm.engine(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.

Build FAILED.

/home/sb/projects/ufm/local-ammps-test/ammps_sharkfin_container/container_contents/ammps_bin/amm.engine(1,1): error MSB4025: The project file could not be loaded. Data at the root level is invalid. Line 1, position 1.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.01
```

**Comment by mesalas** [comment]
The DLLs in `ammps_sharkfin_container/container_contents/ammps_bin` in ammps_sharkfin_container are already compiled binaries. They can be executed like this `dotnet amm.engine.dll RunConfFromFile [path to ammps config] [name for output dir] --number [simulation number]`

if we are using rabbitMQ we need to point to the server and specify a queue like this:
`dotnet amm.engine.dll RunConfFromFile [path to ammps config] [name for output dir] --number [simulation number] --rabbitMQ-host [address for rabbitmq server] --rabbitMQ-queue [rabbitmq queue to use] -t true`
The final `-t` option is for throttling the logger to reduce the size of the output a bit. Not important for single local runs but doing many runs on cloud we want to throttle.

**Comment by sbenthall** [comment]
Got it. Builidng the AMMPS binary is no longer a SHARKFin problem:

https://github.com/sbenthall/SHARKFin/commit/cfcbf9122e6114a9b6d2f3ff953c2e39e7e06fc7
