### ISSUE TITLE
changes to macro_update...

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#132]
- No solve() at the beginning of the method
- assign solution for agent's 'true' expectations.
- simulate using the 'fake' expectation -- because we don't want the assets to grow.

https://github.com/sbenthall/SHARKFin/blob/master/sharkfin/population.py#L811-L831

- Allow agents to Adjust their allocation in HARK during this step -- they might have dividends to reinvest or otherwise have significant wealth/income changes.
- Compute the new share demand in the macro day as a target (maybe using `compute_share_demand`)
- Update `agent.shares` and return the delta.
  -  Note this used to be negative only, to represent sales for consumption. Now it can be positive, because of e.g. reinvested dividends.

**Comment by alanlujan91** [comment]
For a macro update:

1. Temporarily save agent's true risky expectations
2. Create dummy expectations for simulation (RiskyAvg = 1.0, RiskyStd = 0)  NOTE: This means we need this point (1, 0) in the master solution state space!
3. Obtain agent's solution functions based on agent's true risky expectations
4. Simulate agent based on dummy expectations to avoid asset growth realization
5. Assign agent's true risky expectations back to agent.

**Comment by alanlujan91** [comment]
For an attend update: 

1. Assign new risky expectations to agent. 
2. Assign solution object based on risky expectations. 
3. Compute share demand
   
Attend looks ok to me, no changes in structure.

**Comment by alanlujan91** [comment]
> Allow agents to Adjust their allocation in HARK during this step -- they might have dividends to reinvest or otherwise have significant wealth/income changes.

This happens by assigning solution based on true_risky_expectations, simulation based on macro_expectations. 

> Compute the new share demand in the macro day as a target (maybe using compute_share_demand)

`macro_update` already creates a delta, no need to use compute_share_demand because `aNrm` is created in simulation
