### ISSUE TITLE
A time series test simulation for AMMPS prices without the macro agents

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#136]
There's some interest in how the AMMPS price process works in the absence of the macro agents, but with the dividend input.

This is a bit like the CalibrationSimulation, but it's to get the statistics (like the kurtosis) of the price process over time.

**Comment by sbenthall** [comment]
It would be good to build this with the ability to have somewhat arbitrary _broker_ processes as well, because that way we can use this to generate data to train an emulator of the AMMPS model.

**Comment by mesalas** [comment]
> There's some interest in how the AMMPS price process works in the absence of the macro agents, but with the dividend input.

@sbenthall wouldnt an easy way to achieve this be making a chum simulation with a much longer delay and setting the buy sell size to 0? afik the chum simulations uses the dividend process. It will not give the ability to test the brokers though.

**Comment by sbenthall** [comment]
I see what you're saying.

I've now made an explicit 'burn-in' mechanism, which runs for some number of days with zero broker activity.
I've disabled tracking/output of prices/dividends/etc. on the burn-in period, as these were supposed to be thrown away.
One way to implement this would be to re-enable tracking on the burn-in period, or have that be optional.

I think that is ultimately messier than what I'd like to do, which is have a way to give an arbitrary series of broker orders to a simulation, in addition to an untracked burn-in period.
That's more general; the CalibrationSimulation then becomes a special case of that SeriesSimulation.

I could see a number of reasons why we would want this in the future:
 - If we want to build an emulator of the market, we would need to sample the market across a wide space of broker-order sequences. This would be a tool for that.
 - If we find that there is a simulation run that's of interest -- say, because it breaks in a mysterious way, or because it exhibits a phenomenon we are interested in, like an asset bubble -- then we might want to rerun that simulation keeping the broker order sequence fixed but varying the market random seed, to see how robust the pricing phenomenon is.

Since it's not a blocking issue, I'd like to put the time into improving the design in a forward-looking way.

**Comment by gms158** [comment]
See and Nicolas-
Based on the below conversation , should we proceed with running a chum simulation now , or are there still some changes that may occur ?
-Gary

**Comment by sbenthall** [comment]
Keep running chum.
The new design should not change the outcomes of the simulation -- it is mainly refactoring SHARKFin internals.

**Comment by gms158** [comment]
Ok
