### ISSUE TITLE
Negative aNrm errors (and zombie containers)

### ISSUE THREAD

**Issue by gms158** [sbenthall/SHARKFin#156]
yaml file

SIMULATIONS:
- simid: 790
  seed: &seedref790 8060
  rabbitMQHost: &hostref790 10.11.3.4
  rabbitMQqueue: &queueref790 whitesharkqueue790
  ammps_config: &ammpsconfigref790 test_conf.xlsx
  sharkfin:
    save_as: ../../output/whiteshark-babyrunv2790
    parameters:
      simulation: Attention
      tag: tag
      seed: *seedref790
      popn: 25
      quarters: 8
      runs: 60
      attention: 0.99
      dphm: 75000
      market: ClientRPCMarket
      dividend_growth_rate: 1.002
      dividend_std: 0.011988
      queue: *queueref790
      rhost: *hostref790
      p1: 0.99
      p2: 0.95
      d1: 60
      d2: 60
  ammps:
    ammps_config_file_name: *ammpsconfigref790
    ammps_output_dir: ammps_test_out790
    parameters:
      number: 0
      rabbitMQ-host: *hostref790
      rabbitMQ-queue: *queueref790
      t: true
  ammps_config_gen:
    parameters:
      seed: *seedref790
      name: *ammpsconfigref790
      days: 480
      out-dir: /usr/simulation/

02/24/2017 00:00:00 : ABC Closing price 132.06 . Simulated in 41.524 seconds
02/27/2017 00:00:00 : ABC Closing price 347.56 . Simulated in 51.95 seconds
2017-02-27 16:00:00.000000 day number: 40. HarkBrokerInstitution-0 did not reach daily target. Target : 451380 . Got: 55382
02/28/2017 00:00:00 : ABC Closing price 345.305 . Simulated in 29.852 seconds
2017-02-28 16:00:00.000000 day number: 41. HarkBrokerInstitution-0 did not reach daily target. Target : 4885545068 . Got: 4965623695
2017-02-28 16:00:00.000000 day number: 41. HarkBrokerInstitution-1 did not reach daily target. Target : -17397722715 . Got: -4965685246
10.11.3.4 whitesharkqueue790 8060 25 8 60 ClientRPCMarket 1.002 0.011988 0.99 75000 0.99 0.95 60.0 60.0 0 0 None
Q-0
waiting for response...
response received:{'BuyTarget': 10216, 'SellTarget': -2470, 'ClosingPrice': 99.91, 'MarketState': 'Normal', 'NextDividend': 0.08151543548751931}
waiting for response...
response received:{'BuyTarget': 341, 'SellTarget': -137, 'ClosingPrice': 96.63, 'MarketState': 'Normal', 'NextDividend': 0.0809965271645425}
waiting for response...
response received:{'BuyTarget': 2667, 'SellTarget': -13242, 'ClosingPrice': 98.36, 'MarketState': 'Normal', 'NextDividend': 0.08346618076224877}
waiting for response...
response received:{'BuyTarget': 7785, 'SellTarget': -2990, 'ClosingPrice': 100.2, 'MarketState': 'Normal', 'NextDividend': 0.08307923726545124}
waiting for response...
response received:{'BuyTarget': 12496, 'SellTarget': -2023, 'ClosingPrice': 102.52, 'MarketState': 'Normal', 'NextDividend': 0.08341306408733162}
waiting for response...
response received:{'BuyTarget': 7607, 'SellTarget': -1431, 'ClosingPrice': 105.58, 'MarketState': 'Normal', 'NextDividend': 0.0851277260661867}
waiting for response...
response received:{'BuyTarget': 1723, 'SellTarget': -3135, 'ClosingPrice': 103.94, 'MarketState': 'Normal', 'NextDividend': 0.08341706977742959}
waiting for response...
response received:{'BuyTarget': 7191, 'SellTarget': 0, 'ClosingPrice': 105.04, 'MarketState': 'Normal', 'NextDividend': 0.0841533827026905}
waiting for response...
response received:{'BuyTarget': 1852, 'SellTarget': -956, 'ClosingPrice': 107.82, 'MarketState': 'Normal', 'NextDividend': 0.08596774540119057}
waiting for response...
response received:{'BuyTarget': 952, 'SellTarget': -3135, 'ClosingPrice': 108.79, 'MarketState': 'Normal', 'NextDividend': 0.08617174358431809}
waiting for response...
response received:{'BuyTarget': 2045, 'SellTarget': -1298, 'ClosingPrice': 106.5, 'MarketState': 'Normal', 'NextDividend': 0.08471604507932444}
waiting for response...
response received:{'BuyTarget': 7317, 'SellTarget': -206, 'ClosingPrice': 107.25, 'MarketState': 'Normal', 'NextDividend': 0.08498550445072639}
waiting for response...
response received:{'BuyTarget': 1681, 'SellTarget': -857, 'ClosingPrice': 105.67, 'MarketState': 'Normal', 'NextDividend': 0.08370736826779818}
waiting for response...
response received:{'BuyTarget': 7185, 'SellTarget': 0, 'ClosingPrice': 108.29, 'MarketState': 'Normal', 'NextDividend': 0.08568333927661276}
waiting for response...
response received:{'BuyTarget': 30, 'SellTarget': -3204, 'ClosingPrice': 106.53, 'MarketState': 'Normal', 'NextDividend': 0.08427161523444851}
waiting for response...
response received:{'BuyTarget': 2642, 'SellTarget': 0, 'ClosingPrice': 108.65, 'MarketState': 'Normal', 'NextDividend': 0.08639358933228607}
waiting for response...
response received:{'BuyTarget': 29, 'SellTarget': -2172, 'ClosingPrice': 107.27, 'MarketState': 'Normal', 'NextDividend': 0.08611156849270112}
waiting for response...
response received:{'BuyTarget': 2059, 'SellTarget': 0, 'ClosingPrice': 107.1, 'MarketState': 'Normal', 'NextDividend': 0.08523338775124978}
waiting for response...
response received:{'BuyTarget': 736, 'SellTarget': 0, 'ClosingPrice': 107.3, 'MarketState': 'Normal', 'NextDividend': 0.08535473305202312}
waiting for response...
response received:{'BuyTarget': 4877, 'SellTarget': 0, 'ClosingPrice': 109.47, 'MarketState': 'Normal', 'NextDividend': 0.08652096074031766}
waiting for response...
response received:{'BuyTarget': 31, 'SellTarget': -4020, 'ClosingPrice': 109.08, 'MarketState': 'Normal', 'NextDividend': 0.08627673878498568}
waiting for response...
response received:{'BuyTarget': 5528, 'SellTarget': 0, 'ClosingPrice': 108.28, 'MarketState': 'Normal', 'NextDividend': 0.08504904972762263}
waiting for response...
response received:{'BuyTarget': 2944, 'SellTarget': 0, 'ClosingPrice': 107.77, 'MarketState': 'Normal', 'NextDividend': 0.0836061743831024}
waiting for response...
response received:{'BuyTarget': 2491, 'SellTarget': 0, 'ClosingPrice': 107.44, 'MarketState': 'Normal', 'NextDividend': 0.08286101032647664}
waiting for response...
response received:{'BuyTarget': 6297, 'SellTarget': -426, 'ClosingPrice': 107.25, 'MarketState': 'Normal', 'NextDividend': 0.0824443696939942}
waiting for response...
response received:{'BuyTarget': 750, 'SellTarget': -6, 'ClosingPrice': 107.88, 'MarketState': 'Normal', 'NextDividend': 0.08283739093909553}
waiting for response...
response received:{'BuyTarget': 1931, 'SellTarget': -394, 'ClosingPrice': 108.45, 'MarketState': 'Normal', 'NextDividend': 0.08267288849448258}
waiting for response...
response received:{'BuyTarget': 27, 'SellTarget': -1583, 'ClosingPrice': 108.72, 'MarketState': 'Normal', 'NextDividend': 0.08206169039465845}
waiting for response...
response received:{'BuyTarget': 4439, 'SellTarget': -1084, 'ClosingPrice': 109.33, 'MarketState': 'Normal', 'NextDividend': 0.0824562769387471}
waiting for response...
response received:{'BuyTarget': 3513, 'SellTarget': -3032, 'ClosingPrice': 110.38, 'MarketState': 'Normal', 'NextDividend': 0.08208621594232933}
waiting for response...
response received:{'BuyTarget': 1449, 'SellTarget': -5773, 'ClosingPrice': 111.38, 'MarketState': 'Normal', 'NextDividend': 0.08295535924404607}
waiting for response...
response received:{'BuyTarget': 953, 'SellTarget': -6715, 'ClosingPrice': 110.47, 'MarketState': 'Normal', 'NextDividend': 0.0824272067021553}
waiting for response...
response received:{'BuyTarget': 9673, 'SellTarget': 0, 'ClosingPrice': 111.23, 'MarketState': 'Normal', 'NextDividend': 0.0834951594804673}
waiting for response...
response received:{'BuyTarget': 29, 'SellTarget': -4355, 'ClosingPrice': 112.06, 'MarketState': 'Normal', 'NextDividend': 0.08371301014064175}
waiting for response...
response received:{'BuyTarget': 28, 'SellTarget': -5201, 'ClosingPrice': 112.28, 'MarketState': 'Normal', 'NextDividend': 0.08349548397545246}
waiting for response...
response received:{'BuyTarget': 7069, 'SellTarget': -445, 'ClosingPrice': 111.42, 'MarketState': 'Normal', 'NextDividend': 0.08422782543917048}
waiting for response...
response received:{'BuyTarget': 11501, 'SellTarget': 0, 'ClosingPrice': 112.55, 'MarketState': 'Normal', 'NextDividend': 0.0854636374030848}
waiting for response...
response received:{'BuyTarget': 12751, 'SellTarget': -9160, 'ClosingPrice': 118.2, 'MarketState': 'Normal', 'NextDividend': 0.0855553076572179}
waiting for response...
response received:{'BuyTarget': 31, 'SellTarget': -17903, 'ClosingPrice': 113.8, 'MarketState': 'Normal', 'NextDividend': 0.08513417302021063}
waiting for response...
response received:{'BuyTarget': 31712, 'SellTarget': -535, 'ClosingPrice': 132.55, 'MarketState': 'Normal', 'NextDividend': 0.08542176357177973}
waiting for response...
response received:{'BuyTarget': 451380, 'SellTarget': -3092, 'ClosingPrice': 349.7, 'MarketState': 'Normal', 'NextDividend': 0.0857591065864615}
waiting for response...
response received:{'BuyTarget': 4885545068, 'SellTarget': -17397722715, 'ClosingPrice': 345.31, 'MarketState': 'Normal', 'NextDividend': 0.08712359133085013}
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
03/01/2017 00:00:00 : ABC Closing price 305.23 . Simulated in 26.133 seconds
2017-03-01 16:00:00.000000 day number: 42. HarkBrokerInstitution-0 did not reach daily target. Target : 649975410 . Got: 652405006
2017-03-01 16:00:00.000000 day number: 42. HarkBrokerInstitution-1 did not reach daily target. Target : -8762536579426 . Got: -652496830
03/02/2017 00:00:00 : ABC Closing price 172.11 . Simulated in 38.555 seconds
2017-03-02 16:00:00.000000 day number: 43. HarkBrokerInstitution-1 did not reach daily target. Target : -21848638102866304 . Got: -50619
Error in received data{"bl": 722795462, "sl": 46612846388217929728, "dividend": 0.0876665406390012, "end_simulation": false} Value was either too large or too small for an Int64.
Connection to queue whitesharkqueue790 on 10.11.3.4 closed
basic_cancel - consumer not found: ctag1.0aa7968c30e54fa8a762116b2aa7a73c
/usr/local/lib/python3.9/site-packages/scipy/stats/_stats_py.py:110: RuntimeWarning: The input array could not be properly checked for nan values. nan values will be ignored.
  warnings.warn("The input array could not be properly "
/usr/simulation/SHARKFin/simulate/run_any_simulation.py:265: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  history_df = pd.DataFrame(dict([(k,pd.Series(v)) for k,v in history.items()]))
Simulation ended
Finished OK for RunConfFromFile test_conf.xlsx ammps_test_out790
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
waiting for response...
response received:{'BuyTarget': 649975410, 'SellTarget': -8762536579426, 'ClosingPrice': 303.87, 'MarketState': 'Normal', 'NextDividend': 0.08907721934486186}
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
waiting for response...
response received:{'BuyTarget': 7914, 'SellTarget': -21848638102866304, 'ClosingPrice': 171.8, 'MarketState': 'Normal', 'NextDividend': 0.08813818439180233}
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
ERROR: Agent with CRRA 3.3333333333333335has negative aNrm after capital gains update.
Setting normalize assets and shares to 0.
waiting for response...
response received:{'BuyTarget': 1, 'SellTarget': 1, 'ClosingPrice': 1, 'MarketState': 'Stopped: Error in received data{"bl": 722795462, "sl": 46612846388217929728, "dividend": 0.0876665406390012, "end_simulation": false} Value was either too large or too small for an Int64.', 'NextDividend': 1}
The market stopped! Do something!
Ending simulation
Market stoped
Length of values (44) does not match length of index (45)
Lengths:{'buy_macro': 45, 'sell_macro': 45, 'owned': 44, 'total_assets': 44, 'mean_income': 44, 'total_consumption': 44, 'expected_ror': 44, 'expected_std': 44}
Length of values (44) does not match length of index (45)
Lengths:{'buy_macro': 45, 'sell_macro': 45, 'owned': 44, 'total_assets': 44, 'mean_income': 44, 'total_consumption': 44, 'expected_ror': 44, 'expected_std': 44}
Length of values (44) does not match length of index (45)
Lengths:{'buy_macro': 45, 'sell_macro': 45, 'owned': 44, 'total_assets': 44, 'mean_income': 44, 'total_consumption': 44, 'expected_ror': 44, 'expected_std': 44}
Failure to compute kurtosis or skew of buy/sell limits
data type <class 'numpy.object_'> not inexact
finished  790

**Comment by sbenthall** [comment]
What was unexpected about the result of running this configuration?

**Comment by sbenthall** [comment]
This created a zombie container.
@mesalas to check locally.

**Comment by sbenthall** [comment]
Ok. There are some big bugs in SHARKFin.

I've added extra transparency into the negative `aNrm` value errors, and ran the model with some extreme values in order to trigger them.

https://gist.github.com/sbenthall/ddfb9cf98844bfbefcf96ba3d3e25e98

One thing that is happening in the simulation, which never should be happening, is agents that have _negative shares_.
But it's happening often when these errors are triggered.

Of course, I need to fix this...

**Comment by sbenthall** [comment]
Split into #160 and https://github.com/mesalas/ammps_sharkfin_container/issues/11
