### ISSUE TITLE
AgentPopulation solution is sometimes returning a negative RiskyShare

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#160]
Under some conditions, the AgentPopulation solution's ShareFunc is returning a _negative_ risky share from its ShareFunc.

Since we use this value to create the agents' target value of share ownership, this wreaks havoc on the simulation.

This is one way to reproduce the error with some standard scripts:

https://gist.github.com/sbenthall/d0b4b581c683a0e3bd0e10b59dd4011d

**Comment by sbenthall** [comment]
Please include an automated unit test along with the fix for this issue.
A failing test that reproduces this error under simple, isolated conditions is a good contribution in its own right, as right now it's hard to know under what conditions the solution function has this error.

**Comment by alanlujan91** [comment]
```
(sharkfin-dev) C:\Users\alujan\GitHub\alanlujan91\SHARKFin>python simulate/run_any_simulation.py --simulation Attention --seed 790 --quarters 3 --attention 0.99 --dphm 1500000 --p1 0.1 --p2 .1 --dividend_growth_rate 1.002 output/20221006_ras_d
Traceback (most recent call last):
  File "C:\Users\alujan\GitHub\alanlujan91\SHARKFin\simulate\run_any_simulation.py", line 10, in <module>
    from simulate.parameters import (
ModuleNotFoundError: No module named 'simulate'
```

How do I set this up?

**Comment by sbenthall** [comment]
Did you go through the installation steps in the README?

(If you did, and are still getting this error, that's a documentation problem I'll need to fix)

**Comment by alanlujan91** [comment]
Yes, and can run tests locally and they all pass. but can't seem to run a simulation on command line

**Comment by alanlujan91** [comment]
The trouble seems to be my environment not recognizing the subdirectory `simulate` as a module. This subdirectory is outside of the `sharkfin` subdirectory.

**Comment by sbenthall** [comment]
I agree with your analysis.
I've made another change.
Try:
 - pulling from master
 - running `pip install -e .` again
 - running the `run_any_simulation` script again
