### ISSUE TITLE
Zero return autocorrelation when broker is inactive

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#173]
We are getting positive return autocorrelation with an inactive broker.
That is not well calibrated!

**Comment by mesalas** [comment]
@sbenthall can you point me to a config that has positive autocorrelation ill pull the data and investigate whats going on.

**Comment by sbenthall** [comment]
'/shared/home/ammpssharkfin/master/allSharkfinrep10data/all/whiteShark10reps1001-whiteShark10reps_sim_stats.txt'

**Comment by sbenthall** [comment]
One explanation for this is that we are including the dividend in the 'return' for the risky asset, and the dividend growth (mean of the random walk) is positive.

**Comment by sbenthall** [comment]
A misunderstanding! The Durbin-Watson test is 2.0 with 0 autocorrelation, < 2.0 for correlation, and > 2.0 for anticorrelation. We have been subtracting 2. So a positive DW - 2 test means anticorrelation.

So:
- our log returns are anticorrelated because of the mean reversion effect of the institutional investors, 
- they become correlated when there's a market failure (because the market is crashing)
- positive correlation of the log squared returns, which is volatility clustering, which is expected!
- more volatility clustering in market failure because things are rapidly getting worse.

**Comment by sbenthall** [comment]
A trend following agent in the market maybe could reduce the anticorrelation of returns by arbitraging on the institutional investor behavior.

**Comment by sbenthall** [comment]
@sbenthall will make the numbers produced by SHARKFin less confusing or better documented.
