### ISSUE TITLE
Lucas 0 should use infinite horizon agents

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#186]
For the simplest Lucas case, the agents are infinite horizon agents.

`cycles=0` must be passed to the `solve` method.

This can profoundly impact the run-time of our simulations, and is a good reason to break off the solution step into a subprocess that can be precomputed for equivalent ex ante populations before running ex post simulations.

This will probably require a core HARK improvement to allow for exported serialized solutions (AgentPopulation Solutions?)

**Comment by sbenthall** [comment]
A few elements to this:

- Separating the solution and simulation scripts in SHARKFin
- Making sure the HARK PopulationSolution can be serialized; see https://github.com/econ-ark/HARK/issues/1211
- Making the backend (computation, SLURM) work with this new architecture

**Comment by alanlujan91** [comment]
At least for Lucas0 definition, since it's a trivial population setting cycles = 0 might increase the time of creating one solution, but there is only 1 solution to compute. So one solution might take longer, but overall it should probably take less time to compute the AgentPopulationSolution object.

**Comment by sbenthall** [comment]
Let's do this locally in the pure python approach first.

Then with advice from Gary and Bill write scripts that compute the solution and save them as a file.

**Comment by alanlujan91** [comment]
This creates a lot of issues with self.Rfree being a list instead of a float, will have to check if this is local bug or HARK bug
