### ISSUE TITLE
AgentPopulationSolution assumes that there are labels to merge_by

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#189]
The AgentPopulationSolution code really is written assuming that there will be some ex post continuous parameters to merge over.

It chokes when you try to pass it None or an empty list to merge_by.

With LUCAS0, we have a simple population with no such continuous, ex post variables. the AgentPopulationSolution code should work in this trivial case.

**Comment by alanlujan91** [comment]
Can you guide me to where in the code this is choking up?

**Comment by sbenthall** [comment]
Here, when None or an empty list is passed in as argument.

https://github.com/sbenthall/SHARKFin/blob/master/sharkfin/population.py#L536-L549
