### ISSUE TITLE
test_simulation.py runs very slowly

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#204]
The automated tests in test_simulation.py hang for an unusually long amount of time.
Would be good to trim this down somehow.

**Comment by alanlujan91** [comment]
This might have to do with the deepcopying of agents when `explode_agents` gets called. One way to reduce this time would be to reduce `num_by_type` parameter, to maybe 2 just for simple testing of the feature.

**Comment by sbenthall** [comment]
You might be right. But I am surprised that deepcopying takes so long. Have you timed it? I know you mentioned it.
If that is the bottleneck, there may be more efficient ways to create multiple identical agents (like, building them all with the AgentType constructor).

Yes, reducing num_by_type for the test would make sense. But

**Comment by sbenthall** [comment]
I think we identified that the problem was #205
