### ISSUE TITLE
Scaling the dividend process relative to the S&P500

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#215]
We have two numbers  for the S&P500, which are the historical mean and standard deviation of its price -- call these $\mu_P$ and $\sigma_P$.

I believe we've settled on how to derive the growth rate and standard deviation from these numbers.

Ultimately, the consumers are interested in the _returns_ on the risky asset, which includes both the price and the dividend.

I believe that implies that the distribution of returns implied by the USUAL expectations is not the same as the distribution over changes to the price.

This is somewhat subtle, and I have code in #210 that makes these adjustments.

The problem I want to raise in this PR is that.... aren't the returns factored into the price of the S&P500, because of how the price is adjusted by the exchange to deduct the value of the dividends? I'm wondering if there's any holes in the logic here.

**Comment by mesalas** [comment]
paper on dividend and variation:

https://www.jstor.org/stable/pdf/24465694.pdf?refreqid=excelsior%3A46d10af3001edcaf36d3f7f5ffde9be0&ab_segments=&origin=&initiator=&acceptTC=1

**Comment by sbenthall** [comment]
As we discussed, I think that the relationship between the price and the dividend, and how it deteriorates as we depart from the LAP assumptions, should be something we write about in the paper.

@mesalas  you convinced me that since in reality the price and dividend are not as related as they are in the LAP model, worrying too much about this point of model calibration is silly.
