### ISSUE TITLE
Default CRRA and DiscFac for SPARK SHARK?

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#216]
What shall we use for CRRA and DiscFac?

**Comment by sbenthall** [comment]
@alanlujan91 @llorracc ? 

This is sort of a research design question.
I can't tell if the research would benefit from looking at a grid of values or not.
(This is the DiscFac and CRRA for the homogeneous consumer population.)
(If we did grid over these values, we would need to make sure that the impatience condition was met.)

**Comment by mesalas** [comment]
That's a good point. Ill make an option for passing CRRA and discount factors into ammps so we can adjust them if needed.

**Comment by sbenthall** [comment]
These are implemented as command line arguments in SHARKFin:
https://github.com/sbenthall/SHARKFin/blob/master/simulate/run_any_simulation.py#L71-L72

I wish I had a better sense of how the parameter grid was being passed through to the command line and AMMPS.

I think that's currently being done in code by @wjt5121 that isn't in a repository?
I would like to be able to verify that the two simulations are synced.

**Comment by sbenthall** [comment]
CRRA as 5.0 and DiscFac as 0.99 are the defaults. 
These numbers passed the impatience condition with the dividend process calibrated to S&P500.
We don't have to rock this boat unless there's a good reason!
