### ISSUE TITLE
First test simulation for combine AMMPS/SHARKFin SPARK run

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#221]
#### Static parameters

SHARKFin
 --quarters 4
--expectations  InferentialExpectations
--expectations  ClientRPCMarket

(use the default CRRA, DiscFac, dividend growth rate and dividend std, p1, p2, AttentionSimulation, LUCAS0 population)

AMMPS
 -days parameter to 240 to simulate a "sharkfin year".

#### Grid - Variation:

Seeds: 10 ?
(SHARKFin -d) 

AMMPS parameters:

- mm_lucas_factor =[0.0,0.15,1.0] 
-  inst_val_std = [0.1,0.2]

SHARKFin parameters:

--attention [0.015, 0.05]
--dphm [1000, 10000]
--zeta [0, 0.3, .7, 1.0]

#### Expected results:

Less MM Lucas factor, more II variation, more attention, higher zeta, higher dphm all contribute to the collapse of the financial system.

#### Other notes

We will continue to use the stripped down version of AMMPs with only MM, II, the Broker, and noise traders. This should have 30 minute runtime, but won't reproduce stylized facts of the stock market.

**Comment by wjt5121** [comment]
960 Simulation Parameter Grid has been initiated. 571 Simulation have completed the remaining are still running. I will update once complete.
I've also attached the parameter grid csv.
[lucasShark2parametergrid.csv](https://github.com/sbenthall/SHARKFin/files/11467577/lucasShark2parametergrid.csv)

**Comment by wjt5121** [comment]
Simulation Update: Simulations 517 through 960 failed tom complete due to the data vol becoming full. 
I re-staged the environment and restarted the simulations which are about 10 mins in. I will update again once the sims are complete and data is available.
I have attached the
