### ISSUE TITLE
join 'all_clean data' and the 'experiment grid' combined as a CSV after a gridded simulation run

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#229]
We have two tables:
 - all_clean, which includes SHARKFin parameters and simulation outputs (dependent variables)_
 - an experiment grid, generated in the simulation configuration process, which includes both AMMPS and SHARKFin parameters

We need to have these combined into one table/CSV, with:
 - one record for each sim
 - the SHARKFin configuration parameters
 - the AMMPS configuration parameters
 - the sim_stats() for each sim, each with its own column.

let's call this the simulation results table/csv/whatever.

**Comment by gms158** [comment]
@sbenthall , I highlighted some parameters below from the azure table to include in the all_clean data file, Let me know if you want less or more.
-Gary

include
**attention
**dphm
**expectations
**inst_val_std
**mmlucasfactor
**quarters
**seed
**simid
**zeta

not include
ammps
ammps_config_cmd
ammps_config_gen
cmdBundle
experimentName
sharkfin
simulation
start_ammps_cmd
start_sharkfin_cmd
status
tag

**Comment by sbenthall** [comment]
That looks good to me, @gms158
