### ISSUE TITLE
local config.yml used for Azure flag even when remote config file is used

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#23]
The flag telling hark_agent_portfolio to use Azure for its market data storage is currently set in a configuration file `config.yml`.

That file path is hardcoded into the python.

https://github.com/sbenthall/HARK_ABM_INTRO_public/blob/8798f374afecf9934e0648b7ca40d031a8ff6751/HARK/hark_portfolio_agents.py#L33-L39

However, this same code gets ran even when the simulation code is being ran with a remotely fetched configuration file, as in the main `run_simulations` script.

This is confusing, as nothing else in the local `config.yml` file is used in this latter case. One would reasonable expect that the remote config file's `azure:` flag would overwrite the local one.

**Comment by sbenthall** [comment]
Depends on #79

**Comment by nicksawhney** [comment]
Once pnl gets moved this will be a non-issue, though this is a good reminder to make sure any azure configuration we need for the current cloud architecture is well-configured. Once PNL is removed, however, no sharkfin library code will have the AZURE flag.
