### ISSUE TITLE
AssertionErorr assert subjective_return < 1

### ISSUE THREAD

**Issue by wjt5121** [sbenthall/SHARKFin#237]
@sbenthall I started to receive the following error when I attempt to start SharkFin. 

------------shark_lucasShark10763_err.log-----
Traceback (most recent call last):
  File "/usr/simulation/SHARKFin/simulate/run_any_simulation.py", line 330, in <module>
    "price_to_dividend_ratio": price_dividend_ratio_random_walk(
  File "/usr/simulation/SHARKFin/simulate/../sharkfin/utilities.py", line 162, in price_dividend_ratio_random_walk
    assert subjective_return < 1
AssertionError
----------------------------------------------

------------stdout.log----------
Sharkfin output : 20.230.0.191 lucasShark10763 45561 25 4 60 ClientRPCMarket InferentialExpectations LUCAS0 5.0 0.99 1.000203 0.011983 0.05 10000 0.1 0.1 60.0 60.0 0.0 0 0 0 None ClosingPrice
subjective_return: 1.0005120714871312
---------------------------------

**Comment by sbenthall** [comment]
https://github.com/sbenthall/SHARKFin/commit/504372d1f647a10b986bf790bd4d38f5b1d220f6
