### ISSUE TITLE
Next simulation --

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#239]
Grid - Variation:

Seeds: 20
(SHARKFin -d)

AMMPS parameters:

    mm_lucas_factor =[0.0, 0.05, 0.15, 1.0]
    inst_val_std = [0.1,0.15, 0.2]

SHARKFin parameters:

--attention [0.005, 0.015, 0.05]
--dphm [1000, 5000, 10000]
--zeta [0, 0.3, .7, 1.0]
--pop_aNrmInitMean [5, 6, 7]

**Comment by sbenthall** [comment]
1296 Grid points; 100 seeds each...

**Comment by wjt5121** [comment]
Updated config generator with pop_aNrmInitMean parameter. I've attached the parameter grid in csv format. 
[sparksharkrun1parametergrid.csv.zip](https://github.com/sbenthall/SHARKFin/files/11803382/sparksharkrun1parametergrid.csv.zip)
