### ISSUE TITLE
Grid order: 2023-07-28

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#254]
The goal of this grid is to get better insight into the phase transition between the Lucasy and crashing phases.

@wjt5121 I think last time you may have set the SHARKFin parameters, but not adjusted the AMMPS parameters. (I.e., I see AMMPS parameters from the previous grid). Please update the AMMPS parameters this time.

------------
seeds = 35

AMMPS parameters:

mmsize = [105]
mm_lucas_factor =[0.0, 0.0001, 0.001, 0.1, 1.0]
inst_val_std = [0.1]

SHARKFin parameters:

--attention [0.001,0.01, 0.1, 1.0]
--dphm [1, 20, 403] # (e^0, e^3, e^6)
--zeta [0, 0.001, 0.01, 0.1, 1.0]
--pop_aNrmInitMean [4, 6, 7, 8, 9, 10, 11, 13]

**Comment by wjt5121** [comment]
@sbenthall Sorry for that, I've double check it this time. There will be 84000 grid points in this run.
Here is a link to the [csv](https://sbsimulationdata.blob.core.windows.net/cyclecloud/tigershark_param_grid.csv?sp=r&st=2023-08-02T12:29:59Z&se=2023-09-02T20:29:59Z&spr=https&sv=2022-11-02&sr=b&sig=xmnQxAcTLSGNlTgE%2Fh65WHvP4Sc4cBgVkxGhLmBdhYo%3D)
 The simulations started yesterday and I will check on it this morning and post the initial results.

**Comment by wjt5121** [comment]
@sbenthall @mesalas 
Here is an update on this grid. 

Total number of simulation is 84000 each with 4 quarters of 60 days for a total of 20160000.
8044 simulations exiting with status 0 and completed all 240 days successfully for a total of 1930560.0
10152 simulations exited with status code 1. Simulations existing with code 1 completed 545730.0 days
6 simulations exited with status code 3. Simulations existing with code 3 completed 664.0 days
The total number of simulated days is 2476954.0 which is 12.286478174603173 percent of the total.

I've attached a csv with the data so far. 
[tigershark_param_grid_partial_results.csv.zip](https://github.com/sbenthall/SHARKFin/files/12261193/tigershark_param_grid_partial_results.csv.zip)

**Comment by sbenthall** [comment]
Thanks Bill

**Comment by sbenthall** [comment]
Has this run completed yet?

**Comment by mesalas** [comment]
No and its going to take a while more. Bill said last Friday that it was about 15% done. The reason that it's taking so long is that we're only running on the one pre paid instance.

We should ask John if we can add some of the cheap spot instances.

**Comment by sbenthall** [comment]
uh huh
