### ISSUE TITLE
intraday 'flash crash' instrumentation

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#267]
In order to look for evidence of 'flash crashes':

- [x] @mesalas release intraday trading range back through the Broker to sharkfin at the end of the day
- [x] @sbenthall aggregation of this into summary statistics per-simulation, which make it into the data output.
  - the range is published by the broker. 
  - mean, standard deviation, max, and min of the range process.
- [x] @johnliechty2 another metric: (price_today - price_yesterday) / range_today, or something like it.
- [x] @sbenthall - max of the z-score process.
- [x] @sbenthall extra process from John: log(1 + Range_t) – log(1 + abv(P_t – P_{t-1}) ).

**Comment by mesalas** [comment]
The intraday range (high-low) is now passed in the JSON string passed from AMMPS to Sharkfin with the key `DailyRange`.
I will test that we can pass this variable when implemented in sharkfin

**Comment by sbenthall** [comment]
This commit adds ranges tracking and reporting to sim_stats:
https://github.com/sbenthall/SHARKFin/commit/b9eeabb6694a64236cb6c836f560ed7b42086035

BUT I wasn't able to test this locally. Looks like README is out of date?
#270

@mesalas please help

**Comment by sbenthall** [comment]
Ok this is implemented now.
