### ISSUE TITLE
stylized facts

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#29]
Add as stats:
 - autocorrelation of the rate of returns
 - autocorrelation of the squared rate of returns

These are the 'stylized facts' about the market that interest Blake LeBaron and those following his work.

These can be output variables returned in sim_states()

**Comment by nicksawhney** [comment]
Is this kind of autocorrelation correct for what we're looking to do here? 
https://stackoverflow.com/questions/643699/how-can-i-use-numpy-correlate-to-do-autocorrelation

**Comment by sbenthall** [comment]
https://iopscience.iop.org/article/10.1088/1469-7688/1/2/304/meta

**Comment by sbenthall** [comment]
@ZDavid

**Comment by sbenthall** [comment]
https://github.com/bashtage/arch
