### ISSUE TITLE
use sequential portfolio consumer type

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#43]
Use the sequential portfolio consumer type properly.

**Comment by sbenthall** [comment]
Or make this the default in HARK.

**Comment by alanlujan91** [comment]
If we are switching to a portfolio model with sticky adjustment, the Sequential share function (with input of resources post consumption) is already handled by `SequentialPortfolioConsumerType`. 

In sum, there are 2 share functions returned by `SequentialPortfolioConsumerType` solver:
- ShareFuncAdj( input: m = cash on hand, liquid assets, total resources) = output: s = risky share of liquid assets post consumption a = m - c
- SequentialShareFuncAdj( input: a = liquid assets post consumption = a = m - c) = output: s = risky share of liquid assets post consumption a = m - c

**Comment by alanlujan91** [comment]
the AgentPopulation demo already uses SequentialPortfolioConsumerType https://github.com/sbenthall/SHARKFin/blob/master/simulate/run_hark_sim.py

is there an additional place where this should be replaced?

**Comment by sbenthall** [comment]
Ah, interesting.

Yes, `run_hark_sim.py` currently uses code that in the `macro/` directory. But that has not yet been integrated into the `sharkfin` package.

Either one of two things needs to happen:
 - your AgentPopulation work gets included into HARK proper, and then imported into SHARKFin
 - your AgentPopulation work gets merged into the `sharkfin.population` module and loaded into all the sharkfin simulations.

I wonder if you could take a look at what's currently in `sharkfin.population` and see how much of what's there is not superceded by your new population code?

https://github.com/sbenthall/SHARKFin/blob/master/sharkfin/population.py

This is connected to #81 -- we need to do some refactoring of how population modeling happens in SHARKFin to integrate your new work and modularize what's already there.

**Comment by sbenthall** [comment]
The new SHARK agent will inherit from this type. #85 

And this is also fixed in this PR: #86
