### ISSUE TITLE
Orchestrate spin-up of rabbitmq and simulations

### ISSUE THREAD

**Issue by nicksawhney** [sbenthall/SHARKFin#59]
Since we're now a "microservices-based scalable simulation platform" its a good idea to think about the timing of spinning up a full simulation automatically. The order must be:
- start RabbitMQ, wait for RabbitMQ to finish starting
- start AMMPs, wait for AMMPs to start listening to RabbitMQ
- start SHARKFin, begin running simulations
- SharkFin sends a close signal to AMMPs, both shut down 
- RabbitMQ is shut down

[Tye](https://github.com/dotnet/tye) has been recommended to handle this timing. I'll also look into what kinds of signals/logs are generated by RabbitMQ that can help with the timing. If this is too complex, I can also try writing a python or bash script that oversees everything.

**Comment by sbenthall** [comment]
See #6 and #66

Right now it's very difficult to do local development on SHARKFin because running a simulation relies on all these undocumented and unscripted extra steps.

**Comment by nicksawhney** [comment]
Yes. There isn't a lot of "code" but there also doesn't need to be much "orchestration" if there already is a rabbitmq container in docker when we spin-up new simulation containers. It's become a non-issue with our architecture, though there is no single command a researcher could use to spin up rabbitMQ, then sharkfin/ammps, then run a simulation that saves the data, so this could be worth building as a feature down the line.
