### ISSUE TITLE
Easier Local Setup

### ISSUE THREAD

**Issue by nicksawhney** [sbenthall/SHARKFin#6]
It's quite clunky to change `AZURE = False` to True every time you want to switch between working locally and in the cloud. It seems like there's been a change in what azure lets you install since the code was written because I can't get an install of azure through pip which contains an `azure.storage` module. It seems they've deprecated the original `pip install azure` in favor of submodules. This means that 1) the azure code should be rewritten and 2) there should be some better way of distinguishing whether you're working locally or on the cloud so you don't have to rewrite code depending on where you're running an experiment.

**Comment by sbenthall** [comment]
Yes, thanks for flagging this.

I was doing this as a workaround to problems I had installing the azure libraries locally.
I fixed that local issue (which was my fault -- I was in a python/pip versioning maze), and now the software has this bad design.

A better place to put this flag -- and other Azure related metadata -- would be in the `config.yml` file.

**Comment by sbenthall** [comment]
Am I mistaken, or was a fix for this committed, which then caused #23 ?

All these Azure configuration related issues should be settled in one clean PR.

**Comment by sbenthall** [comment]
Finished?

**Comment by nicksawhney** [comment]
moving pnl to an external package fixes all these weird azure issues, and they were also resolved when tests were updated after the mess of the last few months was cleaned up.
