### ISSUE TITLE
Rethink configuration files

### ISSUE THREAD

**Issue by nicksawhney** [sbenthall/SHARKFin#61]
Before the integration with AMMPS, we have had one configuration file for SHARKFin and one for the market simulation. However, as development has continued we (I) have been more haphazard with configuration. For example, the "azure" flag shows up in multiple configuration files, and we have had options for running a local simulation. As we think about moving the sharkfin-rabbitmq-ammps setup to the cloud, we should think about how to set up cloud configuration, and whether we need to rethink which parameters are included in the ammps, sharkfin, and cloud configuration files respectively. Simplifying and documenting this setup will help avoid technical debt as we try to turn this project into a reusable software library.

**Comment by sbenthall** [comment]
- PyNetLogo configs should of course be optional... Make PyNetLogo an optional dependency. Progress towards this can come from splitting up the main hark_portfolio_agents.py file into separate submodules.
- AMMPS configuration is in memory as several Pandas dataframes and typically gets exported to Excel, but could be read/written in other formats that are more Unix friendly. Maybe check to see if Pandas can export to YAML?

**Comment by mesalas** [comment]
Heres an example of an AMMPS config example

[1_scale-1.0_nmm-9.xlsx](https://github.com/sbenthall/SHARKFin/files/8227155/1_scale-1.0_nmm-9.xlsx)

**Comment by sbenthall** [comment]
Depends on #79

**Comment by sbenthall** [comment]
Now this is connected to #95 for the AMMPS stuff.
