### ISSUE TITLE
Configure rabbitMQ queue

### ISSUE THREAD

**Issue by nicksawhney** [sbenthall/SHARKFin#69]
We need to make the queue name (and maybe the network address) for rabbitMQ configurable in order to allow one rabbitmq instance to handle multiple sharkfin-ammps pairs. It is quite simple to make the queue name an argument to the ClientRPCMarket class, but should this be added to the main config file we use as well? It may be nice to have a separation of simulation parameters and other miscellaneous parameters (such as the AZURE flag, or RabbitMQ parameters). This should also work elegantly with the docker images @mesalas is setting up, which seem to rely on environment variables at the moment.

**Comment by nicksawhney** [comment]
partially addressed in the `ammps-integration` branch

**Comment by sbenthall** [comment]
Is `ammps-integration` destined to be merged to `master`?

**Comment by nicksawhney** [comment]
`ammps-integration` should not be merged into master as it was a temporary fix and we no longer use it. However, the rabbitMQ parameters are now configurable from a previous chum PR.
