### ISSUE TITLE
MarketPNL Java Error

### ISSUE THREAD

**Issue by nicksawhney** [sbenthall/SHARKFin#72]
The only test that is currently failing is the test that runs a full NetLogo simulation.

`java.lang.java.lang.NoClassDefFoundError: java.lang.NoClassDefFoundError: org/nlogo/workspace/Controllable

../ve2/lib/python3.9/site-packages/jpype/_jclass.py:99: java.lang.NoClassDefFoundError`

NetLogo simulations work as intended (if the NetLogo installation is in the `sharkfin` directory) but the test doesn't seem to access java properly. We have also had discussions of deprecating NetLogo entirely. 

How should I move forward on this?

**Comment by sbenthall** [comment]
I've commented out this test.

I've also fixed the import path of `pnl_utils` so now there is no test failure:
https://github.com/sbenthall/SHARKFin/commit/a36477c789923f7e3fec6f62ca6b0c53dfff972c

I've made a specialized issue for the fate of the PNL dependency as a whole: #74
