### ISSUE TITLE
duplicate code

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#75]
With some recent changes, there are several cases where code is duplicated.
 - hark_portfolio_agents.FinanceModel and expectations.FinanceModel
 - hark_portfolio_agents.Broker and broker.Broker

Maybe it's just that hark_portfolio_agents hasn't yet been refactored away in the rest of the library?

**Comment by nicksawhney** [comment]
I wanted to talk to you about this in our meeting today. We have a few old scripts and notebooks that we don’t use for anything or aren’t really useful (like test_rpc.py) that still rely on hark_portfolio_agents.py

we can:
keep the monolithic file to keep those notebooks and scripts compatible
remove the file and notebooks/scripts
update everything

**Comment by sbenthall** [comment]
Let's sort this out before the 0.2 release as it's hard to navigate

I think the downstream stuff should be updated if important or removed if not.
