### ISSUE TITLE
stable random seed for random number generation in SHARKFin

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#89]
HARK and AMMPS are fixed to a random seed.

SHARKFin needs to be set up so the random see for each random draw uses the same random number generator with a seed set at the beginning.

**Comment by sbenthall** [comment]
I think this has already been implemented. Is that correct @nicksawhney ? If so, please close this issue

**Comment by sbenthall** [comment]
@gms158

**Comment by mesalas** [comment]
In my understanding its implemented.

**Comment by sbenthall** [comment]
I think that makes sense.
It will take some more work to run that seed through the python simulation code but that's a fine idea for the interface.
I'll have a PR for you to look at before our meeting today.

**Comment by sbenthall** [comment]
What needs to consume this seed?

- The Market, which will be generating a stochastic exogenous dividend stream.
- The AgentPopulation, which will pass this to the macro agents (but probably with a different, newly computed, seed for each agent, so they are not all using the same seed). See #85 #110 
- Any stochastic parts of the simulation, such as the random draws for daily attention -- though this will be moving the to agent classes as well. see #85 again

**Comment by sbenthall** [comment]
As long as we are consistently using the numpy random number generator, I think we can set this seed in just one place with `numpy.random.seed()`. We are not using multi-threading, so there are no weird race conditions that would disrupt the determinism here.

**Comment by sbenthall** [comment]
No, `np.random.seed()` is deprecated.

**Comment by sbenthall** [comment]
@alanlujan91 I've worked a stable Numpy Random Number Generator through the current AgentPopulation and AgentList classes as part of this work.

We will need to revisit this with the new AgentPopulation implementation to make sure the RNG is being passed through and used correctly.
