### ISSUE TITLE
Rename this repository

### ISSUE THREAD

**Issue by sbenthall** [sbenthall/SHARKFin#9]
This repository's name is not good.

We should talk with the larger team and come up with a more compelling code name for this work.

**Comment by sbenthall** [comment]
Desideratum: Includes the letters "ark". that would help it fit into the "Econ-ARK" suite of tools, notionally.

**Comment by alanlujan91** [comment]
FinARK or FinMARK - Financial Market Agent Resource toolKit

**Comment by sbenthall** [comment]
What about SHARKFin?

Simulating Heterogenous Agents Resource toolKit with Finance

**Comment by nicksawhney** [comment]
MARKT - Market Agent Resource Toolkit, pronounced "Market"

**Comment by sbenthall** [comment]
Compare: https://en.wikipedia.org/wiki/Finnmark

**Comment by alanlujan91** [comment]
now I'm wondering why HARK isn't SHARK

**Comment by sbenthall** [comment]
I'm declaring victory for SHARKFin, which elicits peals of delighted laughter whenever it is mention. It is a fine name.
