### ISSUE TITLE
Problem with logging prices in CHUM simulation

### ISSUE THREAD

**Issue by mesalas** [sbenthall/SHARKFin#91]
It seems that there is an issue with the collection of prices in the chum simulation.

Below is an example. the broker buys 5000 shares on day 30 (the 31'th simulated day).
Notice how the price starts at 99.51 and keeps falling until it ends at 16.93 on the last day. If we compare the price with the closing price (last traded price) in ammps it should be 94.42

<img width="912" alt="image" src="https://user-images.githubusercontent.com/2293808/164460844-013bf7a4-c5cf-41da-b987-583157ae8727.png">

So either ammps is not sending the correct price to sharkfin or sharkfin is logging it wrong.
@mesalas check the prices ammps sends.
@nicksawhney check if there is an error in the way that the prices are logged.

best regards
Nicholas

**Comment by nicksawhney** [comment]
This has been resolved.
